# Generated by Django 5.1.6 on 2025-03-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('profilepicture', models.ImageField(upload_to='photos')),
                ('gender', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
            ],
        ),
    ]
