# Generated by Django 5.1.6 on 2025-03-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='catname',
        ),
    ]
