# Generated by Django 5.1.6 on 2025-03-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_category_name_category_catname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
            preserve_default=False,
        ),
    ]
