# Generated by Django 5.1.6 on 2025-03-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
        ),
    ]
