# Generated by Django 5.1.6 on 2025-03-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_product_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellerid',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
            preserve_default=False,
        ),
    ]
