# Generated by Django 5.1.6 on 2025-03-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_product_sellerid_product_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel'),
        ),
    ]
