# Generated by Django 5.1.6 on 2025-03-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_sellerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
