# Generated by Django 5.1.6 on 2025-03-31 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_pimage_productimage_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('budget', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('msg', models.TextField()),
                ('timestamp', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('resolve', 'resolve')], default='pending', max_length=40)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel')),
            ],
        ),
    ]
