# Generated by Django 5.1.6 on 2025-04-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_inquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inquiry',
            new_name='productinquiry',
        ),
    ]
